### ISSUE TITLE
 Runtime Error: ValueError During Inference with Provided Environment

### ISSUE THREAD

**Issue by panli0** [RoyiRa/Syntax-Guided-Generation#9] opened 2024-11-22 15:46 UTC
When running the project with the environment specified in environment.yaml, I encountered the following runtime error during inference:

ValueError: not enough values to unpack (expected 3, got 2)

This happens during attention processing.

Steps to Reproduce
Create the environment using the provided environment.yaml:

conda env create -f environment.yaml
conda activate syngen
Run the script:

python run.py --prompt "a horned lion and a spotted monkey" --seed 1269
The error occurs during runtime.

Environment
Python: 3.11.2 (as specified in environment.yaml)
diffusers: 0.21.1
torch: 2.0.1
OS: Windows Server 2022
CUDA: 11.8

Request
Could you confirm if the current setup is compatible or provide guidance to fix the issue? Thank you!

**Comment by eranhirs** [comment] 2024-11-25 09:15
Thanks for opening an issue! I was unable to reproduce this specific error, could you please provide additional details? Specifically, the exception trace would be useful to compare that we have the same code base.

Please note that there was a different issue, regarding a [breaking change](https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0) from the `huggingface_hub` library. This was fixed so you will need to update your codebase and recreate the environment to avoid this error.

**Comment by panli0** [comment] 2024-11-26 11:30
Thank you for your response and for providing the updated environment.yaml. I set up a fresh environment based on the updated dependencies and encountered the following error during inference:

Error Traceback:

Traceback (most recent call last):
  File "run.py", line 87, in <module>
    main(args.prompt, args.seed, args.output_directory, args.model_path, args.step_size, args.attn_res,
  File "run.py", line 10, in main
    image = generate(pipe, prompt, seed, step_size, attn_res)
  File "run.py", line 24, in generate
    result = pipe(prompt=prompt, generator=generator, syngen_step_size=step_size,
  File "syngen_diffusion_pipeline.py", line 280, in __call__
    latents = self._syngen_step(
  File "syngen_diffusion_pipeline.py", line 373, in _syngen_step
    self.unet(
  File "diffusers/models/unet_2d_condition.py", line 956, in forward
    sample, res_samples = downsample_block(
  File "diffusers/models/unet_2d_blocks.py", line 1086, in forward
    hidden_states = attn(
  File "diffusers/models/transformer_2d.py", line 315, in forward
    hidden_states = block(
  File "diffusers/models/attention.py", line 218, in forward
    attn_output = self.attn2(
  File "diffusers/models/attention_processor.py", line 420, in forward
    return self.processor(
  File "diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py", line 146, in __call__
    key = attn.head_to_batch_dim(key)
  File "diffusers/models/attention_processor.py", line 437, in head_to_batch_dim
    batch_size, seq_len, dim = tensor.shape
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by panli0** [comment] 2024-11-26 13:35
Thank you for your guidance. After creating a new environment using the updated environment.yaml file, I was able to run the inference successfully. I’m considering using your implementation as a foundation for exploring related tasks in my research. I truly appreciate your inspiring research and the excellent codebase you’ve shared.

**Comment by eranhirs** [comment] 2024-11-28 11:43
Thanks for the update! Closing this issue now.

**Closed as completed by eranhirs** 2024-11-28 11:43 UTC
